services:
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
  #   depends_on:
  #     - mongo
  #     # - postgres
  #   env_file:
  #     - .env

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: payload
      MONGO_INITDB_ROOT_PASSWORD: payload

  # Uncomment the following to use postgres
  # postgres:
  #   # restart: always
  #   image: postgres:latest
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: payload
  #     POSTGRES_USER: payload

volumes:
  data:
  # pgdata:
  # node_modules:
